apiVersion: v1
kind: Secret
metadata:
  name: node-mongo-secret
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASS: ZXhhbXBsZQ==
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ==
